### ISSUE TITLE
Can you help to build popular disassembler?

### ISSUE THREAD

**Issue by silverwolfceh** [j4k0xb/View8#1]
Hi @j4k0xb ,

Would you please help to build some popular disassemblers? For example, 10.6.194.26 and latest node 20 lts?

**Comment by j4k0xb** [comment]
https://github.com/suleram/View8/releases has node 20
I can help you build a specific version if there are problems, not doing it myself for a bunch of versions because it would take forever.

Currently searching for a way to make it version-agnostic:
- either writing a parser from scratch: https://swarm.ptsecurity.com/how-we-bypassed-bytenode-and-decompiled-node-js-bytecode-in-ghidra
- or instrumenting unmodified node/electron binaries: https://github.com/j4k0xb/View8/tree/v8-frida/v8-frida

**Comment by silverwolfceh** [comment]
Thanks for feedback.

For this version (10.6.194.26), I am having issue when compiling it (required clang, it is existed but can't solve). 

If you have time, please help me with it.

Many thanks.

**Comment by j4k0xb** [comment]
for electron/chromium you need to add these flags to args.gn:
```ini
v8_enable_sandbox = true
v8_enable_pointer_compression = true
```

change this line to `GetActiveBytecodeArray()` for example, since there's no `isolate` variable:
https://github.com/j4k0xb/View8/blob/3e7d952f42f3c0fba738b0cf3b78a370331eadd6/Disassembler/v8.patch#L18

to make it work for different versions, remove this check from `src/snapshot/deserializer.cc`:
```cpp
CHECK_EQ(magic_number_, SerializedData::kMagicNumber);
```

then build v8 and afterwards the disassembler:
```sh
clang++ v8dasm.cpp -g -std=c++17 -Iinclude -Lout.gn/x64.release/obj -lv8_libbase -lv8_libplatform -lv8_monolith -o v8dasm -DV8_COMPRESS_POINTERS -DV8_ENABLE_SANDBOX
```

I'll also update the readme guide and patches to reflect these changes

**Comment by silverwolfceh** [comment]
> I have updated the readme guide and patches to be more clear and work with electron
> 
> Also tested it and got it working for your version on linux (your choice to trust or self-build): [v8dasm.zip](https://github.com/user-attachments/files/16651926/v8dasm.zip)

Thank you so much. Not that I didn't trust you but it is missing dynamic library. 
By the way, I will try to figure out myself.
